### PR TITLE
Writeods

### PR DESCRIPTION
**Pull request by pbrohan**
Revert to using `utils::zip` rather than `zip::zip` as something about the zip files upsets Excel.

Change `cat` to `writeLines`, which is slightly faster, and performs less conversion of text to try and help with UTF-8 problems on old version of R. This didn't help.

Fixed a bug where if a cell's contents was `<text:p/>`, the reader would crash.

### CODE REVIEW

**Comment by chainsawriot** [comment]
@pbrohan Thanks a lot again!

One tiny issue: #99 While `zip` is available on Mac and Linux, not all Windows users have RTools (which has `zip`) installed on their machines. And `utils::zip` is written in a way that does not give any feedback for missing `zip` in the path.

https://github.com/wch/r-source/blob/1028337671367f51a84ced997772a2173d1c6b3b/src/library/utils/R/zip.R#L100-L125

Now there is a struggle between producing Excel-incompatible ODS files (using current `zip::zip`) or some Windows users might find that this package does not write any ODS file (using `utils::zip`). Excel is a proprietary monster we can't do anything about, but allowing `write_ods` to write Excel-incompatible ODS is a bad approach. Therefore, I think we should revert back to `utils::zip`. That's how the current v1.8.0 works anyway. A simple solution is to improve the documentation: Saying that Windows users should install RTools. (I believe the easiest way is `installr::install.Rtools`) In long term, we can either work with [r-lib/zip](https://github.com/r-lib/zip) or even the R Core to improve their `zip` offerings.

**Comment by pbrohan** [comment]
I agree. It's not an ideal solution. 

Sadly I don't know enough about zip files to understand what's wrong. Windows can read the zip files produced by `zip` fine, and only produces an error when Excel tries to open the ODS file, so it's difficult to work out exactly what's the error actually is. The error message just says that it has repaired the file, with no indication as to what the error actually was.

`openxlsx` uses `zip` and clearly Excel accepts that, so I'll see if I can copy what they did, maybe there are some settings I don't understand!

**Comment by pbrohan** [comment]
Nevermind. Reading through the openxlsx code, their settings seem to fix it. Still no idea why.

**Comment by pbrohan** [comment]
OoO, Concerning.

**Comment by chainsawriot** [comment]
@pbrohan Thanks a lot again! I can confirm that this can generate Excel compatible ODS files (I tried both online 365 and iOS). As well as Google Sheets. Wonderful work!

The issue now is LibreOffice Calc. I am using 7.3.7.2. But it complaints about "The data could not be loaded completely because the maximum number of columns per sheet was exceed." My version should be able to [open 16384 columns](https://wiki.documentfoundation.org/Faq/Calc/022). I attempted to change the magic numbers 16383 and 16384 in `.write_sheet_con` to other small numbers. The numbers that work are 1023/1024. And sure enough with 1024, Excel and Google Sheets still work.

I was wondering, should we make this `max(cols, 1024)`?

If you don't mind, could you please also update `NEWS.md`? I can do that too.

**Comment by pbrohan** [comment]
Will do. 

That's interesting. Can you open `excel_repeat.ods` in the `testdata` folder, which also has 16384 columns?

**Comment by chainsawriot** [comment]
@pbrohan Thank you very much!

To clarify, I **can** open those files with Calc 7.3, but Calc gives the warning message ( "The data could not be loaded completely because the maximum number of columns per sheet was exceed." ). And opening `excel_repeat.ods` gives the same warning message; and then a 22x2 sheet.

**Comment by pbrohan** [comment]
Hmm. It looks like that's an incompatibility between LibreOffice and Excel.

By default Excel defines the file to have the maximum possible size (16384 x 1048576) and just adds repeated blank columns and rows to pad the sheet (which is why I added the guard on `write_ods` to refuse to try and write dataframes bigger than this). This isn't required by the OpenDocument Spec though

LibreOffice by the looks of things doesn't do this, and only defines columns it actually needs. 

I think the best compromise is to still refuse to write files larger than 16383 x 1048576, even though these are legitimate ODS files, but to use a default column width of 1024, unless the data is wider than that, in which case use 16384, which is the reported max width for new versions of LibreOffice. 
I'd rather not give a warning on the console, as strictly speaking, having > 1024 columns doesn't go against the ODS spec, but I'll add a note to the readme about old versions of Excel and LibreOffice not supporting this.

**Comment by chainsawriot** [comment]
@pbrohan I like the approach.

**Comment by pbrohan** [comment]
Ok, hopefully that will work. I _think_ that this has also gone some way to fixing the legacy R character encodings on Windows, but I am too suspicious of Windows R's string conversions to be truly confident :). (I had missed a line that got written without conversion to UTF-8)

**Comment by chainsawriot** [comment]
@pbrohan Thank you very much! The big three (Excel, Calc, Google Sheets) all work. I will merge this.

**Pull request merged**
